# Generated by Django 4.2.25 on 2026-02-15 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер кімнати')),
                ('room_type', models.CharField(choices=[('single', 'Одномісна'), ('double', 'Двомісна'), ('suite', 'Люкс')], max_length=20, verbose_name='Тип кімнати')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за ніч')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Кімната',
                'verbose_name_plural': 'Кімнати',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оцінка від 1 до 5', verbose_name='Оцінка')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.room', verbose_name='Кімната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name="Ім'я гостя")),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('check_in', models.DateField(verbose_name='Заїзд')),
                ('check_out', models.DateField(verbose_name='Виїзд')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронювання')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Кімната')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
